redis:
    host: 10.252.252.67 #127.0.0.1
    port: 6379
    password: 'charles'
    broker: 5                    # broker for celery
    backend: 6                   # backed for celery
    cache: 1

db:
    host: 10.252.252.67 #127.0.0.1 #
    port: 3306
    user: charles
    password: charles@orderplus
    db_name: facebook
    db_type: mysql

account:
    login_interval: 3600