redis:
    host: 47.112.113.252 #10.252.252.67
    port: 6379
    password: 'charles'
    broker: 5                    # broker for celery
    backend: 6                   # backed for celery
    cache: 1

db:
    host: 47.112.113.252 # 10.252.252.67
    port: 3306
    user: charles
    password: charles@orderplus
    db_name: facebook
    db_type: mysql

account:
    login_interval: 300         # 账号登录的最小间隔时间
    local_photo_path: resource/photos/    # 账号图象的本地存储位置
    remote_photo_path: ftp://xxx.xx.xx/ab/cc    # 账号图象的服务器存储位置