redis:
    host: 47.112.113.252 #10.252.252.67
    port: 6379
    password: 'charles'
    broker: 4                    # broker for celery
    backend: 5                   # backed for celery
    cache: 6

db:
    host: 47.112.113.252 # 10.252.252.67
    port: 3306
    user: charles
    password: charles@orderplus
    db_name: facebook_test
    db_type: mysql

account:
    login_interval: 600         # 账号登录的最小间隔时间
    verify_interval: 36000        # 账号验证的时长
    post_interval: 36000          # 账号发状态的间隔时间
    add_friend_interval: 86400          # 添加好友间隔时间
    local_photo_path: resource/photos/    # 账号图象的本地存储位置
    remote_photo_path: ftp://xxx.xx.xx/ab/cc    # 账号图象的服务器存储位置
    feed_limit: 10                  # 最低养号次数，当账号成功登录次数大于该值时，账号才可用于其他用途，否则只能时行登录浏览

task:
    job_timeout: 3600               # job的超时时间3600秒,即1小时
    job_update_period: 180          # job每次更新的时间段默认为180秒
    one_time_task_timeout: 3600    # 一次性任务的超时时间为1小时天, 3600秒
    cycle_task_timeout: 86400    # 周期任务的超时时间为1天
    update_interval: 30         # 测试环境，任务的更新周期，默认为30秒

system:
    screenshots_dir: screenshots    # 截图保存目录
    screenshots_keep: 10             # 默认保存最近15天的截图

support:
    captcha_in_api = "http://2captcha.com/in.php"
    captcha_res_api = "http://2captcha.com/res.php"
    captcha_api_key = "f4f632da069e2208dd4e5ede45efd683"